#!/usr/bin/env python
# encoding: utf-8

"""
Waf build script for hexacopter control system
Integrates with ArduPilot build system
"""

def build(bld):
    # Build hexacopter control library
    bld.ap_stlib(
        name = 'AP_HexacopterControl',
        ap_vehicle = 'ArduCopter',
        ap_libraries = [
            'AP_Common',
            'AP_Math', 
            'AP_HAL',
            'AP_Param',
            'AP_Motors',
            'AP_Logger',
        ],
        source = [
            'src/hexacopter_sysid.cpp',
            'src/ekf_attitude_velocity.cpp', 
            'src/velocity_feedback_controller.cpp',
        ],
        includes = [
            'include',
        ],
    )